For word 현지지도

In [1]:
series1 = {'2000': 1901,
  '2001': 1999,
  '2002': 1989,
  '2003': 1351,
  '2004': 1243,
  '2005': 1135,
  '2006': 1289,
  '2007': 1387,
  '2008': 1738,
  '2009': 1528,
  '2010': 1472,
  '2011': 0,
  '2012': 400,
  '2013': 1324,
  '2014': 1504,
  '2015': 1067,
  '2016': 1347}

series2 = {'2000': 12,
  '2001': 19,
  '2002': 13,
  '2003': 5,
  '2004': 18,
  '2005': 8,
  '2006': 2,
  '2007': 5,
  '2008': 11,
  '2009': 11,
  '2010': 33,
  '2011': 37,
  '2012': 34,
  '2013': 12,
  '2014': 20,
  '2015': 15,
  '2016': 29}

In [5]:
import pandas as pd

df = pd.DataFrame([series1, series2]).T
df.columns = ['newspaper', 'magazine']
df

      newspaper  magazine
2000       1901        12
2001       1999        19
2002       1989        13
2003       1351         5
2004       1243        18
2005       1135         8
2006       1289         2
2007       1387         5
2008       1738        11
2009       1528        11
2010       1472        33
2011          0        37
2012        400        34
2013       1324        12
2014       1504        20
2015       1067        15
2016       1347        29

In [7]:
import scipy.stats as stats

stats.pearsonr(df.newspaper, df.magazine)

(-0.5143131348274291, 0.034669435745011655)

In [11]:
from statsmodels.tsa.stattools import grangercausalitytests

grangercausalitytests(df, maxlag=3)

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=4.2970  , p=0.0586  , df_denom=13, df_num=1
ssr based chi2 test:   chi2=5.2887  , p=0.0215  , df=1
likelihood ratio test: chi2=4.5694  , p=0.0325  , df=1
parameter F test:         F=4.2970  , p=0.0586  , df_denom=13, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.6806  , p=0.1169  , df_denom=10, df_num=2
ssr based chi2 test:   chi2=8.0417  , p=0.0179  , df=2
likelihood ratio test: chi2=6.4389  , p=0.0400  , df=2
parameter F test:         F=2.6806  , p=0.1169  , df_denom=10, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=4.1258  , p=0.0559  , df_denom=7, df_num=3
ssr based chi2 test:   chi2=24.7548 , p=0.0000  , df=3
likelihood ratio test: chi2=14.2548 , p=0.0026  , df=3
parameter F test:         F=4.1258  , p=0.0559  , df_denom=7, df_num=3

{1: ({'ssr_ftest': (4.297030646944522, 0.05861850132717365, 13.0, 1),
   'ssr_chi2test': (5.288653103931719, 0.021464815198072043, 1),
   'lrtest': (4.569367846489797, 0.03254857409554258, 1),
   'params_ftest': (4.2970306469445285, 0.058618501327173465, 13.0, 1.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x1be59b50248>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x1be59f55ec8>,
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (2.6805798736260487, 0.11691762157573503, 10.0, 2),
   'ssr_chi2test': (8.041739620878147, 0.017937356052556655, 2),
   'lrtest': (6.438857043803438, 0.03997789822701408, 2),
   'params_ftest': (2.680579873626051, 0.11691762157573483, 10.0, 2.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x1be59b57748>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x1be59b57988>,
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (4.125799420586709, 0.05588424483203418, 7.0, 3),
   'ssr_chi2test': (24.75479652352026, 1.737482770692303e-05, 3),
   'lrtest': (14.254760796863508, 0.0025781116597648306, 3),
   'params_ftest': (4.125799420587413, 0.05588424483201407, 7.0, 3.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x1be59d57148>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x1be59d57888>,
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])])}

For word 농장

In [13]:
series3 = {'2000': 45,
  '2001': 112,
  '2002': 58,
  '2003': 67,
  '2004': 120,
  '2005': 152,
  '2006': 51,
  '2007': 46,
  '2008': 112,
  '2009': 82,
  '2010': 108,
  '2011': 138,
  '2012': 191,
  '2013': 135,
  '2014': 295,
  '2015': 172,
  '2016': 74}
series4 = {'2000': 8893,
  '2001': 7091,
  '2002': 6304,
  '2003': 5808,
  '2004': 6867,
  '2005': 10556,
  '2006': 12376,
  '2007': 9662,
  '2008': 9181,
  '2009': 6656,
  '2010': 7938,
  '2011': 6006,
  '2012': 5444,
  '2013': 7310,
  '2014': 7977,
  '2015': 4607,
  '2016': 5953}

In [15]:
df2 = pd.DataFrame([series3, series4]).T
df2.columns = ['newspaper', 'magazine']
df2

      newspaper  magazine
2000         45      8893
2001        112      7091
2002         58      6304
2003         67      5808
2004        120      6867
2005        152     10556
2006         51     12376
2007         46      9662
2008        112      9181
2009         82      6656
2010        108      7938
2011        138      6006
2012        191      5444
2013        135      7310
2014        295      7977
2015        172      4607
2016         74      5953

In [17]:
stats.pearsonr(df2.newspaper, df2.magazine)

(-0.23482771213039677, 0.36427475195964276)

In [18]:
grangercausalitytests(df2, maxlag=3)

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.7438  , p=0.4041  , df_denom=13, df_num=1
ssr based chi2 test:   chi2=0.9154  , p=0.3387  , df=1
likelihood ratio test: chi2=0.8902  , p=0.3454  , df=1
parameter F test:         F=0.7438  , p=0.4041  , df_denom=13, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.9154  , p=0.4315  , df_denom=10, df_num=2
ssr based chi2 test:   chi2=2.7461  , p=0.2533  , df=2
likelihood ratio test: chi2=2.5217  , p=0.2834  , df=2
parameter F test:         F=0.9154  , p=0.4315  , df_denom=10, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.9644  , p=0.4610  , df_denom=7, df_num=3
ssr based chi2 test:   chi2=5.7865  , p=0.1225  , df=3
likelihood ratio test: chi2=4.8432  , p=0.1836  , df=3
parameter F test:         F=0.9644  , p=0.4610  , df_denom=7, df_num=3

{1: ({'ssr_ftest': (0.7437820360035736, 0.40408127914803327, 13.0, 1),
   'ssr_chi2test': (0.9154240443120906, 0.33867934432262775, 1),
   'lrtest': (0.8901943809179897, 0.3454246379635447, 1),
   'params_ftest': (0.7437820360035731, 0.40408127914803327, 13.0, 1.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x1be59f5f048>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x1be59f5fcc8>,
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.915354374787454, 0.43146560927451955, 10.0, 2),
   'ssr_chi2test': (2.746063124362362, 0.2533377849935805, 2),
   'lrtest': (2.5217024161247252, 0.28341268063783626, 2),
   'params_ftest': (0.9153543747874497, 0.431465609274521, 10.0, 2.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x1be59b3b6c8>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x1be59b3b788>,
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.9644223771791101, 0.46099628218264266, 7.0, 3),
   'ssr_chi2test': (5.78653426307466, 0.12247047553621272, 3),
   'lrtest': (4.843220045960351, 0.1836439583942674, 3),
   'params_ftest': (0.964422377179114, 0.460996282182641, 7.0, 3.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x1be59f64488>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x1be59f64a88>,
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])])}